/**
* @file commerror.h
* @brief error code table
* @version  1.0
* @author Liug
* @date 2012-06-06
*/
#ifndef _COMMERROR_H_
#define _COMMERROR_H_

/**<ERROR Definition*/

#define FAIL_RS232_LIB_BASE					(-2000)
#define FAIL_RS232_INVAILIDPARAM			(FAIL_RS232_LIB_BASE - 1)
#define FAIL_RS232_INIT						(FAIL_RS232_LIB_BASE - 2)
#define FAIL_RS232_WRITE					(FAIL_RS232_LIB_BASE - 3)
#define FAIL_RS232_READ						(FAIL_RS232_LIB_BASE - 4)
#define FAIL_RS232_CLEARBUF					(FAIL_RS232_LIB_BASE - 5)
#define FAIL_RS232_TIMEOUT					(FAIL_RS232_LIB_BASE - 6)
#define FAIL_RS232_RXOOVER					(FAIL_RS232_LIB_BASE - 7)


#define FAIL_SYN_DIAL_LIB_BASE    			(-2100)
#define FAIL_SYN_DIAL_INVAILIDPARAM			(FAIL_SYN_DIAL_LIB_BASE - 1)
#define FAIL_SYN_DIAL_INIT					(FAIL_SYN_DIAL_LIB_BASE - 2)
#define FAIL_SYN_DIAL_PREDIAL				(FAIL_SYN_DIAL_LIB_BASE - 3)
#define FAIL_SYN_DIAL_LINE					(FAIL_SYN_DIAL_LIB_BASE - 4)
#define FAIL_SYN_DIAL_OTHERMACHINE			(FAIL_SYN_DIAL_LIB_BASE - 5)
#define FAIL_SYN_DIAL_CHECK					(FAIL_SYN_DIAL_LIB_BASE - 6)
#define FAIL_SYN_DIAL_NODIALTONE			(FAIL_SYN_DIAL_LIB_BASE - 7)
#define FAIL_SYN_DIAL_NOCARRIER				(FAIL_SYN_DIAL_LIB_BASE - 8)
#define FAIL_SYN_DIAL_BUSY					(FAIL_SYN_DIAL_LIB_BASE - 9)
#define FAIL_SYN_DIAL_ERROR					(FAIL_SYN_DIAL_LIB_BASE - 10)
#define FAIL_SYN_DIAL_NOPREDIAL				(FAIL_SYN_DIAL_LIB_BASE - 11)
#define FAIL_SYN_DIAL_UNKNOW				(FAIL_SYN_DIAL_LIB_BASE - 12)
#define FAIL_SYN_DIAL_WRITE					(FAIL_SYN_DIAL_LIB_BASE - 13)
#define FAIL_SYN_DIAL_READ					(FAIL_SYN_DIAL_LIB_BASE - 14)
#define FAIL_SYN_DIAL_HANGUP				(FAIL_SYN_DIAL_LIB_BASE - 15)
#define FAIL_SYN_DIAL_TELNO					(FAIL_SYN_DIAL_LIB_BASE - 16)

#define FAIL_ASYN_DIAL_LIB_BASE				(-2200)
#define FAIL_ASYN_DIAL_INVAILIDPARAM		(FAIL_ASYN_DIAL_LIB_BASE - 1)
#define FAIL_ASYN_DIAL_INIT					(FAIL_ASYN_DIAL_LIB_BASE - 2)
#define FAIL_ASYN_DIAL_PREDIAL				(FAIL_ASYN_DIAL_LIB_BASE - 3)
#define FAIL_ASYN_DIAL_LINE					(FAIL_ASYN_DIAL_LIB_BASE - 4)
#define FAIL_ASYN_DIAL_OTHERMACHINE			(FAIL_ASYN_DIAL_LIB_BASE - 5)
#define FAIL_ASYN_DIAL_CHECK				(FAIL_ASYN_DIAL_LIB_BASE - 6)
#define FAIL_ASYN_DIAL_NODIALTONE			(FAIL_ASYN_DIAL_LIB_BASE - 7)
#define FAIL_ASYN_DIAL_NOCARRIER			(FAIL_ASYN_DIAL_LIB_BASE - 8)
#define FAIL_ASYN_DIAL_BUSY					(FAIL_ASYN_DIAL_LIB_BASE - 9)
#define FAIL_ASYN_DIAL_ERROR				(FAIL_ASYN_DIAL_LIB_BASE - 10)
#define FAIL_ASYN_DIAL_NOPREDIAL			(FAIL_ASYN_DIAL_LIB_BASE - 11)
#define FAIL_ASYN_DIAL_UNKNOW				(FAIL_ASYN_DIAL_LIB_BASE - 12)
#define FAIL_ASYN_DIAL_WRITE				(FAIL_ASYN_DIAL_LIB_BASE - 13)
#define FAIL_ASYN_DIAL_READ					(FAIL_ASYN_DIAL_LIB_BASE - 14)
#define FAIL_ASYN_DIAL_HANGUP				(FAIL_ASYN_DIAL_LIB_BASE - 15)
#define FAIL_ASYN_DIAL_CLEARBUF				(FAIL_ASYN_DIAL_LIB_BASE - 16)
#define FAIL_ASYN_DIAL_TELNO				(FAIL_ASYN_DIAL_LIB_BASE - 17)

#define FAIL_TCPIP_LIB_BASE					(-2300)
#define FAIL_TCPIP_INVAILIDPARAM			(FAIL_TCPIP_LIB_BASE - 1)
#define FAIL_TCPIP_SETLOCALIP				(FAIL_TCPIP_LIB_BASE - 2)
#define FAIL_TCPIP_OPEN						(FAIL_TCPIP_LIB_BASE - 3)
#define FAIL_TCPIP_BIND						(FAIL_TCPIP_LIB_BASE - 4)
#define FAIL_TCPIP_DHCP						(FAIL_TCPIP_LIB_BASE - 5)
#define FAIL_TCPIP_CONNECTNULL				(FAIL_TCPIP_LIB_BASE - 6)
#define FAIL_TCPIP_CONNECT					(FAIL_TCPIP_LIB_BASE - 7)
#define FAIL_TCPIP_WRITE					(FAIL_TCPIP_LIB_BASE - 8)
#define FAIL_TCPIP_READ				    	(FAIL_TCPIP_LIB_BASE - 9)
#define FAIL_TCPIP_CLOSE					(FAIL_TCPIP_LIB_BASE - 10)
#define FAIL_TCPIP_WAIT						(FAIL_TCPIP_LIB_BASE - 11)

#define FAIL_TCPIP_SINGLE_SSL_OPEN			(FAIL_TCPIP_LIB_BASE - 12)
#define FAIL_TCPIP_MUTURE_SSL_OPEN			(FAIL_TCPIP_LIB_BASE - 13)
#define FAIL_TCPIP_SSL_SERVERCERT_LOAD		(FAIL_TCPIP_LIB_BASE - 14)
#define FAIL_TCPIP_SSL_CLIENTCERT_LOAD		(FAIL_TCPIP_LIB_BASE - 15)
#define FAIL_TCPIP_SSL_CLIENTKEY_LOAD		(FAIL_TCPIP_LIB_BASE - 16)
#define FAIL_TCPIP_SSL_CONNECT				(FAIL_TCPIP_LIB_BASE - 17)
#define FAIL_TCPIP_SSL_WRITE				(FAIL_TCPIP_LIB_BASE - 18)
#define FAIL_TCPIP_SSL_READ					(FAIL_TCPIP_LIB_BASE - 19)
#define FAIL_TCPIP_SSL_DISCONNECT			(FAIL_TCPIP_LIB_BASE - 20)
#define FAIL_TCPIP_SSL_CLOSE				(FAIL_TCPIP_LIB_BASE - 21)

#define FAIL_TCPIP_ADD_DNS_IP				(FAIL_TCPIP_LIB_BASE - 22)
#define FAIL_TCPIP_GET_DN_ADDRESS			(FAIL_TCPIP_LIB_BASE - 23)
#define FAIL_TCPIP_SETALIVE					(FAIL_TCPIP_LIB_BASE - 24)

#define FAIL_TCPIP_ETH_PULLOUT				(FAIL_TCPIP_LIB_BASE - 25)
#define FAIL_ETH_DEVICE_OPEN				(FAIL_TCPIP_LIB_BASE - 26)


#define FAIL_WIRELESS_LIB_BASE				(-2400)
#define FAIL_WIRELESS_INVAILIDPARAM			(FAIL_WIRELESS_LIB_BASE - 1)
#define FAIL_WIRELESS_NO_SIM				(FAIL_WIRELESS_LIB_BASE - 2)
#define FAIL_WIRELESS_PIN					(FAIL_WIRELESS_LIB_BASE - 3)
#define FAIL_WIRELESS_LOCKED				(FAIL_WIRELESS_LIB_BASE - 4)
#define FAIL_WIRELESS_UNDEFINE				(FAIL_WIRELESS_LIB_BASE - 5)
#define FAIL_WIRELESS_EMPTY					(FAIL_WIRELESS_LIB_BASE - 6)
#define FAIL_WIRELESS_INIT					(FAIL_WIRELESS_LIB_BASE - 7)
#define FAIL_WIRELESS_SIGNAL				(FAIL_WIRELESS_LIB_BASE - 8)
#define FAIL_WIRELESS_PPP_CONFIG			(FAIL_WIRELESS_LIB_BASE - 9)
#define FAIL_WIRELESS_PPP_DIAL				(FAIL_WIRELESS_LIB_BASE - 10)
#define FAIL_WIRELESS_PPP_CHECK				(FAIL_WIRELESS_LIB_BASE - 11)
#define FAIL_WIRELESS_PPP_DISCONNECT		(FAIL_WIRELESS_LIB_BASE - 12)
#define FAIL_WIRELESS_PPP_GETADDR			(FAIL_WIRELESS_LIB_BASE - 13)
#define FAIL_WIRELESS_PPP_HANGUP			(FAIL_WIRELESS_LIB_BASE - 14)
#define FAIL_WIRELESS_REGISTER				(FAIL_WIRELESS_LIB_BASE - 15) /**< used for NEW_API */
#define FAIL_WIRELESS_GETENABLE				(FAIL_WIRELESS_LIB_BASE - 16) /**< used for NEW_API */
#define FAIL_WIRELESS_GET_SIM				(FAIL_WIRELESS_LIB_BASE - 17) /**< used for NEW_API */

#define FAIL_WIFI_LIB_BASE					(-2500)
#define FAIL_WIFI_INVAILIDPARAM				(FAIL_WIFI_LIB_BASE - 1)
#define FAIL_WIFI_INIT						(FAIL_WIFI_LIB_BASE - 2)
#define FAIL_WIFI_CONNECT					(FAIL_WIFI_LIB_BASE - 3)
#define FAIL_WIFI_CHECK						(FAIL_WIFI_LIB_BASE - 4)
#define FAIL_WIFI_CONNECTED					(FAIL_WIFI_LIB_BASE - 5)
#define FAIL_WIFI_GETADDR					(FAIL_WIFI_LIB_BASE - 6)
#define FAIL_WIFI_SHUTDOWN					(FAIL_WIFI_LIB_BASE - 7)
#define FAIL_WIFI_SCAN						(FAIL_WIFI_LIB_BASE - 8)
#define FAIL_WIFI_GET_SSIDMODE				(FAIL_WIFI_LIB_BASE - 9)
#define FAIL_WIFI_RIGSTERSIGNAL				(FAIL_WIFI_LIB_BASE - 10) /**< used for NEW_API */
#define FAIL_WIFI_ENABLE					(FAIL_WIFI_LIB_BASE - 11) /**< used for NEW_API */
#define FAIL_WIFI_DISABLE					(FAIL_WIFI_LIB_BASE - 12) /**< used for NEW_API */
#define FAIL_WIFI_ADDNETWORK				(FAIL_WIFI_LIB_BASE - 13) /**< used for NEW_API */
#define FAIL_WIFI_GETRESULT					(FAIL_WIFI_LIB_BASE - 14) /**< used for NEW_API */

#define FAIL_MODEM_LIB_BASE					(-2600)
#define FAIL_MODEM_INVAILIDPARAM			(FAIL_MODEM_LIB_BASE - 1)
#define FAIL_MODEM_INIT						(FAIL_MODEM_LIB_BASE - 2)
#define FAIL_MODEM_PPP_CHECK				(FAIL_MODEM_LIB_BASE - 3)
#define FAIL_MODEM_PPP_DISCONNECT			(FAIL_MODEM_LIB_BASE - 4)
#define FAIL_MODEM_PPP_GETADDR				(FAIL_MODEM_LIB_BASE - 5)
#define FAIL_MODEM_PPPCFG					(FAIL_MODEM_LIB_BASE - 6)
#define FAIL_MODEM_DIAL						(FAIL_MODEM_LIB_BASE - 7)
#define FAIL_MODEM_DIAL_LINE				(FAIL_MODEM_LIB_BASE - 8)
#define FAIL_MODEM_DIAL_OTHERMACHINE		(FAIL_MODEM_LIB_BASE - 9)
#define FAIL_MODEM_DIAL_1630				(FAIL_MODEM_LIB_BASE - 10)
#define FAIL_MODEM_PPPDIAL					(FAIL_MODEM_LIB_BASE - 11)
#define FAIL_MODEM_READ						(FAIL_MODEM_LIB_BASE - 12)
#define FAIL_MODEM_WRITE					(FAIL_MODEM_LIB_BASE - 13)
#define FAIL_MODEM_PPPHANGUP				(FAIL_MODEM_LIB_BASE - 14)
#define FAIL_MODEM_SHUTDOWN					(FAIL_MODEM_LIB_BASE - 15)
#endif

